#!/bin/sh

[ -z "$1" ] && echo "Usage: $0 <figure name>" && exit 1
[ ! -f "$1.svg" ] && echo "File $1.svg not found" && exit 1

## Export Inkscape SVG to PDF+LaTeX code
inkscape "$1.svg" --export-area-drawing --export-dpi=300 --export-latex --export-filename="$1.pdf"

## Disable interpolation in the PDF (to conform with PDF/A standard)
# sed -i 's|/Interpolate true$|/Interpolate false|' "$1.pdf" # sometimes CORRUPTS the PDF
## https://stackoverflow.com/questions/20011515/how-to-remove-anti-aliasing-in-pdf-images
perl -M-encoding -0777pe "s|/Interpolate true|' 'x17|ge" <"$1.pdf" >"$1-fixed.pdf"

## Add watermark to the PDF (if watermark script is available)
directory=$(dirname "$1")
if [ -f "$directory/add-watermark" ]; then
    ## try to extract the author's name from the LaTeX preamble
    author_name=$(sed -n 's/^[^%].*ThesisAuthorPlaintext}{}{\(.*\)}$/\1/p' preamble/data.tex)
    ## if the `\ThesisAuthorPlaintext` command is commented out, extract from the `\ThesisAuthor` command
    [ -z "$author_name" ] && author_name=$(sed -n 's/.*ThesisAuthor}{}{\(.*\)}$/\1/p' preamble/data.tex)
    ## use just ASCII characters, see https://unix.stackexchange.com/a/653210
    author_name=$(echo "$author_name" | uconv -x Latin-ASCII)

    watermark_string="$(date +%Y) $author_name"  # prepend the year
    # watermark_string="$(date +%Y) Author's Name" # NOTE: or manually edit the watermark string here

    ## use the `add-watermark` script to insert the watermark into the PDF
    "$directory"/add-watermark "$1-fixed.pdf" "$watermark_string"
fi

mv "$1-fixed.pdf" "$1.pdf"
