name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ## thanks to https://github.com/exaexa/better-mff-thesis
  ##       and https://github.com/mff-cuni-cz/cuni-thesis-validator
  build:
    name: Build PDF and upload as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          texlive_version: latest # must be `2024` or later (`latest` chosen by default)
          extra_system_packages: coreutils icu inkscape # `coreutils` for `mktemp`, `icu` for `uconv`
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: |
            README.md
            thesis.pdf
  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: ghcr.io/jdujava/cuni-thesis-validator }
    steps:
      - name: Get the PDF file from the artifact
        uses: actions/download-artifact@v4
      - name: Verify the PDF file with VeraPDF
        run: verify Thesis/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0" failedJobs="0"'

  ## inspired by https://github.com/Pseudomanifold/latex-mimosis
  deploy:
    name: Deploy latest build of PDF and README.md to gh-pages branch
    if: github.event_name == 'push' # only deploy on push
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Get the PDF and README.md from the artifact
        uses: actions/download-artifact@v4
      - name: Commit and push the PDF and README.md to `gh-pages` branch
        run: |
          cd Thesis
          git init -b temp
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[CI] Update to latest PDF and README.md"
          git push --force origin temp:gh-pages
